version: '3.2'
services:
    app:
        build: .
        ports:
            - "4000:4000"
        depends_on:
            - db
        restart: always
        volumes: 
            - /app/node_modules
            - .:/app    
        networks: 
            - net    
    db:     
        networks: 
            - net
        restart: always
        build: ./database
        ports: 
            - "5432:5432"
        volumes: 
            - data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: 123456
            POSTGRES_USER: postgres
            POSTGRES_DB: test
            #PGDATA: /tmp          
networks: 
    net: 
        driver: bridge 
volumes:
    data:
        external: true                    
